name: get-bun-version-with-proto
description: Outputs Bun version from .prototools.
outputs:
  bun-version:
    value: ${{ steps.sha.outputs.sha }}
    description: Bun version.
runs:
  using: composite
  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Output Bun version
      shell: bash
      id: bun-version
      run: |
        VER=$(rg "^bun =" .prototools | awk '{print $3}' | sed 's/"//g')
        echo "bun-version=${VER}" >> "${GITHUB_OUTPUT}"
        echo "$VER"
