name: get-bun-version-with-proto
description: Outputs Bun version from .prototools.
outputs:
  bun-version:
    value: ${{ steps.runner.outputs.bun-version }}
    description: Bun version.
runs:
  using: composite
  steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: Output Bun version
      shell: bash
      id: runner
      run: |
        VER=$(grep "^bun =" .prototools | awk '{print $3}' | sed 's/"//g')
        echo "bun-version=${VER}" >> "${GITHUB_OUTPUT}"
        echo "$VER"
