name: get-bun-version-with-proto
description: Outputs Bun version from .prototools.
outputs:
  bun-version:
    value: ${{ steps.runner.outputs.bun-version }}
    description: Bun version.
runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Output Bun version
      shell: bash
      id: runner
      run: |
        VER=$(grep "^bun =" .prototools | awk '{print $3}' | sed 's/"//g')
        echo "bun-version=${VER}" >> "${GITHUB_OUTPUT}"
        echo "$VER"
