name: Check bun.lockb differences
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  checkBunLockb:
    name: Check bun.lockb differences
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Get Bun ver
        uses: ./.github/actions/get-bun-version-with-proto
        id: bun-version
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ steps.bun-version.outputs.bun-version }}
      - name: Setup deps
        run: bun install --yarn
      - name: check lock diff
        run: diff <(bun bun.lockb) yarn.lock
